FROM ghcr.io/puppeteer/puppeteer:<PPTR_VERSION>

ENV APPLICATION_USER=pptruser \
    APPLICATION_GROUP=pptruser \
    PPTR_VERSION=<PPTR_VERSION> \
    PATH="/home/pptruser/tools:${PATH}"

COPY tools tools

RUN mkdir screenshots

#RUN apt-get install -y libgbm-dev

ADD ./fonts /usr/share/fonts/msfonts

RUN yarn global add pm2 \
    && yarn cache clean \
    && mkdir -p /apps \
    && chown -R $APPLICATION_USER:$APPLICATION_GROUP /apps

RUN echo "Asia/Shanghai" > /etc/timezone
