name: build-image

on:
  push:
    branches:
      - "*"

jobs:
  docker-latest:
    if: ${{ !startsWith(github.ref, 'refs/heads/feature/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set env
        run: echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: arbing/docker-puppeteer-screenshot:${{ env.TAG }}
